app:
  minDelaySeconds: 4
  maxDelaySeconds: 10
  topic:
    pingPong: pingpong
kafka:
  bootstrapServers: localhost:9092
  kafkaAppId: ping-pong
  autoOffsetReset: latest
  teamAGroupId: team-a
  teamBGroupId: team-b